---
- name: Testing andrewrothstein.conjurcli
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'conjur -v'
      ansible.builtin.command: conjur -v
      changed_when: false
      register: conjurcli_test_output
    - name: Output from 'conjur -v'
      ansible.builtin.debug:
        msg: '{{ conjurcli_test_output.stdout }}'
